#ifndef GERMAN_RUBY_BATTLE_SCRIPT_OPCODES_H
#define GERMAN_RUBY_BATTLE_SCRIPT_OPCODES_H

#include <stdint.h>

#define GERMAN_BATTLE_SCRIPT_OPCODE_COUNT 248u
#define GERMAN_BATTLE_SCRIPT_OPCODE_MAX   0xF7u

#if defined(GERMAN_RUBY_DEBUG)
#define GERMAN_BATTLE_SCRIPT_COMMAND_TABLE_ADDRESS 0x082208A4u
#else
#define GERMAN_BATTLE_SCRIPT_COMMAND_TABLE_ADDRESS 0x0820770Cu
#endif

#endif
