#ifndef GERMAN_RUBY_BATTLE_INTERFACE_H
#define GERMAN_RUBY_BATTLE_INTERFACE_H

#define GERMAN_BATTLE_HP_BAR_TILES        6u
#define GERMAN_BATTLE_HP_BAR_PIXELS      48u
#define GERMAN_BATTLE_EXP_BAR_TILES       8u
#define GERMAN_BATTLE_EXP_BAR_PIXELS     64u

#define GERMAN_HP_BAR_HIGH_MIN_PIXELS    25u
#define GERMAN_HP_BAR_MID_MIN_PIXELS     10u
#define GERMAN_HP_BAR_LOW_MIN_PIXELS      1u

#define GERMAN_BATTLE_PARTY_SUMMARY_SLOTS 6u
#define GERMAN_LEVEL_SEPARATOR_IS_PERIOD  1u

#endif
