#ifndef GERMAN_RUBY_BERRY_BLENDER_PLAY_TIME_H
#define GERMAN_RUBY_BERRY_BLENDER_PLAY_TIME_H

#define GERMAN_BLENDER_MAX_PLAYERS 4u
#define GERMAN_BLENDER_FLAVOURS    5u

#define GERMAN_PLAY_TIME_MAX_HOURS   999u
#define GERMAN_PLAY_TIME_MAX_MINUTES  59u
#define GERMAN_PLAY_TIME_MAX_SECONDS  59u
#define GERMAN_PLAY_TIME_MAX_VBLANKS  59u

#endif
