#ifndef GERMAN_RUBY_COORD_EVENT_WEATHER_H
#define GERMAN_RUBY_COORD_EVENT_WEATHER_H

#define GERMAN_COORD_EVENT_WEATHER_RETAIL_START 0x080696ACu
#define GERMAN_COORD_EVENT_WEATHER_RETAIL_END   0x0806977Cu
#define GERMAN_COORD_EVENT_WEATHER_DEBUG_START  0x0806DD88u
#define GERMAN_COORD_EVENT_WEATHER_DEBUG_END    0x0806DE58u

#define GERMAN_COORD_EVENT_WEATHER_SIZE         0x000000D0u
#define GERMAN_COORD_EVENT_WEATHER_DEBUG_DELTA  0x000046DCu
#define GERMAN_COORD_EVENT_WEATHER_WRAPPER_COUNT 13u
#define GERMAN_COORD_EVENT_WEATHER_WRAPPER_SIZE 12u

#define GERMAN_FIELD_TASKS_RETAIL_START 0x0806977Cu
#define GERMAN_FIELD_TASKS_DEBUG_START  0x0806DE58u

#endif
