#ifndef GERMAN_RUBY_DAYCARE_H
#define GERMAN_RUBY_DAYCARE_H

#define GERMAN_DAYCARE_PARENT_SLOTS        2u
#define GERMAN_DAYCARE_INHERITED_IVS       3u
#define GERMAN_DAYCARE_EGG_MOVE_SCAN_MAX  10u
#define GERMAN_DAYCARE_COMPAT_MAX          70u
#define GERMAN_DAYCARE_EGG_CHECK_STEPS    256u

#endif
