#ifndef GERMAN_RUBY_EGG_HATCH_H
#define GERMAN_RUBY_EGG_HATCH_H

#define GERMAN_EGG_HATCH_LEVEL            5u
#define GERMAN_EGG_HATCH_MOVE_SLOTS       4u
#define GERMAN_EGG_HATCH_IV_COUNT         6u
#define GERMAN_EGG_HATCH_FRIENDSHIP     120u
#define GERMAN_EGG_SHARD_VELOCITY_COUNT  19u

#endif
