#ifndef GERMAN_RUBY_FIELD_TASKS_H
#define GERMAN_RUBY_FIELD_TASKS_H

#define GERMAN_FIELD_TASKS_RETAIL_START 0x0806977Cu
#define GERMAN_FIELD_TASKS_RETAIL_END   0x0806A668u
#define GERMAN_FIELD_TASKS_DEBUG_START  0x0806DE58u
#define GERMAN_FIELD_TASKS_DEBUG_END    0x0806ED44u

#define GERMAN_FIELD_TASKS_SIZE         0x00000EECu
#define GERMAN_FIELD_TASKS_DEBUG_DELTA  0x000046DCu

#define GERMAN_FIELD_TASKS_CALLBACK_COUNT 8u
#define GERMAN_FIELD_TASKS_CALLBACKS_RETAIL 0x08381B4Cu
#define GERMAN_FIELD_TASKS_CALLBACKS_DEBUG  0x0839ACF4u

#define GERMAN_FIELD_TASKS_MAP_OFFSET 7u
#define GERMAN_MUDDY_SLOPE_MAX_ACTIVE 4u
#define GERMAN_MUDDY_SLOPE_LIFETIME   32u

#define GERMAN_CLOCK_RETAIL_START 0x0806A668u
#define GERMAN_CLOCK_DEBUG_START  0x0806ED44u

#endif
