#ifndef GERMAN_RUBY_FIELD_CAMERA_H
#define GERMAN_RUBY_FIELD_CAMERA_H

#define GERMAN_FIELD_CAMERA_RETAIL_START 0x08057CFCu
#define GERMAN_FIELD_CAMERA_RETAIL_END   0x080586B8u
#define GERMAN_FIELD_CAMERA_DEBUG_START  0x0805C1E4u
#define GERMAN_FIELD_CAMERA_DEBUG_END    0x0805CBA0u
#define GERMAN_FIELD_CAMERA_TEXT_SIZE    0x000009BCu
#define GERMAN_FIELD_CAMERA_DEBUG_DELTA  0x000044E8u

#define GERMAN_FIELD_CAMERA_BG_TILEMAP_TILES       32u
#define GERMAN_FIELD_CAMERA_VISIBLE_METATILES      16u
#define GERMAN_FIELD_CAMERA_METATILE_TILE_DIM        2u
#define GERMAN_FIELD_CAMERA_METATILE_U16_ENTRIES     8u
#define GERMAN_FIELD_CAMERA_BG_TILEMAP_BYTES      0x800u
#define GERMAN_FIELD_CAMERA_BG3_FILL_TILE        0x3014u

#define GERMAN_FIELD_CAMERA_BG1_VRAM_OFFSET      0xE800u
#define GERMAN_FIELD_CAMERA_BG2_VRAM_OFFSET      0xE000u
#define GERMAN_FIELD_CAMERA_BG3_VRAM_OFFSET      0xF000u

#define GERMAN_FIELD_DOOR_RETAIL_START 0x080586B8u
#define GERMAN_FIELD_DOOR_DEBUG_START  0x0805CBA0u
#define GERMAN_FIELD_DOOR_TILE_VRAM     0x06007F00u

#endif
