#ifndef GERMAN_RUBY_FIELD_MESSAGE_BOX_H
#define GERMAN_RUBY_FIELD_MESSAGE_BOX_H

#define GERMAN_FIELD_MESSAGE_BOX_RETAIL_START 0x08064DB4u
#define GERMAN_FIELD_MESSAGE_BOX_RETAIL_END   0x08065000u
#define GERMAN_FIELD_MESSAGE_BOX_DEBUG_START  0x080693B4u
#define GERMAN_FIELD_MESSAGE_BOX_DEBUG_END    0x08069600u

#define GERMAN_FIELD_MESSAGE_BOX_SIZE         0x0000024Cu
#define GERMAN_FIELD_MESSAGE_BOX_DEBUG_DELTA  0x00004600u

#define GERMAN_FIELD_MESSAGE_BOX_MODE_IWRAM   0x030005A8u
#define GERMAN_FIELD_MESSAGE_BOX_WINDOW_RETAIL 0x0202E87Cu
#define GERMAN_FIELD_MESSAGE_BOX_WINDOW_DEBUG  0x0202EB20u

#define GERMAN_FIELD_MESSAGE_BOX_MODE_HIDDEN      0u
#define GERMAN_FIELD_MESSAGE_BOX_MODE_UNUSED      1u
#define GERMAN_FIELD_MESSAGE_BOX_MODE_NORMAL      2u
#define GERMAN_FIELD_MESSAGE_BOX_MODE_AUTO_SCROLL 3u

#define GERMAN_EVENT_OBJECT_LOCK_RETAIL_START 0x08065000u
#define GERMAN_EVENT_OBJECT_LOCK_DEBUG_START  0x08069600u

#endif
