#ifndef GERMAN_RUBY_FIELDMAP_H
#define GERMAN_RUBY_FIELDMAP_H

#define GERMAN_FIELDMAP_RETAIL_START 0x080562D0u
#define GERMAN_FIELDMAP_RETAIL_END   0x080570DCu
#define GERMAN_FIELDMAP_DEBUG_START  0x0805A7B8u
#define GERMAN_FIELDMAP_DEBUG_END    0x0805B5C4u
#define GERMAN_FIELDMAP_SIZE         0x00000E0Cu
#define GERMAN_FIELDMAP_DEBUG_DELTA  0x000044E8u

#define GERMAN_MAPGRID_METATILE_ID_MASK 0x03FFu
#define GERMAN_MAPGRID_COLLISION_MASK   0x0C00u
#define GERMAN_MAPGRID_COLLISION_SHIFT  10u
#define GERMAN_MAPGRID_ELEVATION_MASK   0xF000u
#define GERMAN_MAPGRID_ELEVATION_SHIFT  12u

#define GERMAN_METATILE_BEHAVIOR_MASK   0x00FFu
#define GERMAN_METATILE_LAYER_MASK      0xF000u
#define GERMAN_METATILE_LAYER_SHIFT     12u

#define GERMAN_MAP_OFFSET               7u
#define GERMAN_BACKUP_MAP_EXTRA_WIDTH  15u
#define GERMAN_BACKUP_MAP_EXTRA_HEIGHT 14u
#define GERMAN_MAX_MAP_DATA_SIZE        0x2800u

#define GERMAN_PRIMARY_METATILES        512u
#define GERMAN_SECONDARY_METATILES      512u
#define GERMAN_PRIMARY_MAP_PALETTES       6u
#define GERMAN_TOTAL_MAP_PALETTES        12u

#define GERMAN_MAPLAYOUT_WIDTH_OFFSET             0x00u
#define GERMAN_MAPLAYOUT_HEIGHT_OFFSET            0x04u
#define GERMAN_MAPLAYOUT_BORDER_OFFSET            0x08u
#define GERMAN_MAPLAYOUT_MAP_OFFSET               0x0Cu
#define GERMAN_MAPLAYOUT_PRIMARY_TILESET_OFFSET   0x10u
#define GERMAN_MAPLAYOUT_SECONDARY_TILESET_OFFSET 0x14u
#define GERMAN_MAPLAYOUT_SIZE                     0x18u

#define GERMAN_MAPGRID_METATILE_ID(cell) \
    ((cell) & GERMAN_MAPGRID_METATILE_ID_MASK)
#define GERMAN_MAPGRID_COLLISION(cell) \
    (((cell) & GERMAN_MAPGRID_COLLISION_MASK) >> GERMAN_MAPGRID_COLLISION_SHIFT)
#define GERMAN_MAPGRID_ELEVATION(cell) \
    (((cell) & GERMAN_MAPGRID_ELEVATION_MASK) >> GERMAN_MAPGRID_ELEVATION_SHIFT)
#define GERMAN_METATILE_BEHAVIOR(attr) \
    ((attr) & GERMAN_METATILE_BEHAVIOR_MASK)
#define GERMAN_METATILE_LAYER_TYPE(attr) \
    (((attr) & GERMAN_METATILE_LAYER_MASK) >> GERMAN_METATILE_LAYER_SHIFT)

#endif
