#ifndef GERMAN_RUBY_ITEM_EFFECT_H
#define GERMAN_RUBY_ITEM_EFFECT_H

#define GERMAN_ITEM_EFFECT_COMMAND_BYTES 6u
#define GERMAN_ITEM_EFFECT_ARG_START     6u

#define GERMAN_ITEM_EFFECT_MOVE_SLOTS    4u
#define GERMAN_ITEM_EFFECT_EV_STATS      6u
#define GERMAN_ITEM_EFFECT_EV_TOTAL_CAP  510u
#define GERMAN_ITEM_EFFECT_EV_ITEM_CAP   100u
#define GERMAN_ITEM_EFFECT_LEVEL_CAP     100u

#endif
