#ifndef GERMAN_RUBY_LOAD_SAVE_H
#define GERMAN_RUBY_LOAD_SAVE_H

#define GERMAN_SAVE_PARTY_SLOTS          6u
#define GERMAN_SAVE_OBJECT_EVENTS       16u
#define GERMAN_SAVE_BAG_ITEMS           20u
#define GERMAN_SAVE_BAG_KEY_ITEMS       20u
#define GERMAN_SAVE_BAG_POKEBALLS       16u
#define GERMAN_SAVE_BAG_TMHM            64u
#define GERMAN_SAVE_BAG_BERRIES         46u
#define GERMAN_SAVE_MAIL_COUNT           16u

#define GERMAN_RETAIL_SAVE_BLOCK_2 0x02024EA4u
#define GERMAN_RETAIL_SAVE_BLOCK_1 0x02025734u
#define GERMAN_DEBUG_SAVE_BLOCK_2  0x02025148u
#define GERMAN_DEBUG_SAVE_BLOCK_1  0x020259D8u

#endif
