#ifndef GERMAN_RUBY_METATILE_BEHAVIOR_H
#define GERMAN_RUBY_METATILE_BEHAVIOR_H

#define GERMAN_METATILE_BEHAVIOR_RETAIL_START 0x080570DCu
#define GERMAN_METATILE_BEHAVIOR_RETAIL_END   0x08057CFCu
#define GERMAN_METATILE_BEHAVIOR_DEBUG_START  0x0805B5C4u
#define GERMAN_METATILE_BEHAVIOR_DEBUG_END    0x0805C1E4u
#define GERMAN_METATILE_BEHAVIOR_TEXT_SIZE    0x00000C20u
#define GERMAN_METATILE_BEHAVIOR_DEBUG_DELTA  0x000044E8u

#define GERMAN_METATILE_BEHAVIOR_COUNT         0xF0u
#define GERMAN_METATILE_BEHAVIOR_MAX           0xEFu

#define GERMAN_TILE_ATTR_WILD_ENCOUNTER         0x01u
#define GERMAN_TILE_ATTR_SURFABLE               0x02u
#define GERMAN_TILE_ATTR_LEGACY_TRAVERSABLE     0x04u
#define GERMAN_TILE_ATTR_MASK                   0x07u

#define GERMAN_METATILE_ATTR_TABLE_RETAIL       0x08314614u
#define GERMAN_METATILE_ATTR_TABLE_DEBUG        0x0832D7BCu
#define GERMAN_METATILE_ATTR_TABLE_SIZE         0x000000F0u

#define GERMAN_METATILE_ATTR_HAS_ENCOUNTER(attr) \
    (((attr) & GERMAN_TILE_ATTR_WILD_ENCOUNTER) != 0)
#define GERMAN_METATILE_ATTR_IS_SURFABLE(attr) \
    (((attr) & GERMAN_TILE_ATTR_SURFABLE) != 0)

#endif
