#ifndef GERMAN_RUBY_NEW_GAME_RUNTIME_H
#define GERMAN_RUBY_NEW_GAME_RUNTIME_H

#define GERMAN_NEW_GAME_STARTING_MONEY 3000u
#define GERMAN_DEBUG_NEW_GAME_MONEY   999999u
#define GERMAN_DEBUG_STARTER_LEVEL        99u

#define GERMAN_NEW_GAME_RETAIL_START 0x08053040u
#define GERMAN_NEW_GAME_DEBUG_START  0x08057230u

#endif
