#ifndef GERMAN_RUBY_OPPONENT_CONTROLLER_H
#define GERMAN_RUBY_OPPONENT_CONTROLLER_H

#define GERMAN_OPPONENT_CONTROLLER_COMMAND_COUNT 57u
#define GERMAN_OPPONENT_CONTROLLER_COMMAND_MAX   0x38u

#if defined(GERMAN_RUBY_DEBUG)
#define GERMAN_OPPONENT_CONTROLLER_TABLE_ADDRESS 0x082210C4u
#else
#define GERMAN_OPPONENT_CONTROLLER_TABLE_ADDRESS 0x08207F2Cu
#endif

#endif
