#ifndef GERMAN_RUBY_OVERWORLD_H
#define GERMAN_RUBY_OVERWORLD_H

#define GERMAN_OVERWORLD_SAVED_OBJECT_TEMPLATES 64u
#define GERMAN_OVERWORLD_LIVE_OBJECT_EVENTS     16u
#define GERMAN_OVERWORLD_LINK_PLAYERS             4u
#define GERMAN_GAME_STAT_MAX                 0xFFFFFFu

#define GERMAN_OVERWORLD_RETAIL_START 0x0805329Cu
#define GERMAN_OVERWORLD_DEBUG_START  0x080575ACu

#endif
