#ifndef GERMAN_RUBY_PLAYER_CONTROLLER_H
#define GERMAN_RUBY_PLAYER_CONTROLLER_H

#define GERMAN_PLAYER_CONTROLLER_COMMAND_COUNT 57u
#define GERMAN_PLAYER_CONTROLLER_COMMAND_MAX   0x38u
#define GERMAN_BATTLE_BUFFER_BYTES_PER_BATTLER 0x200u
#define GERMAN_OTHER_MENU_TILE_OFFSET          444u

#if defined(GERMAN_RUBY_DEBUG)
#define GERMAN_PLAYER_CONTROLLER_TABLE_ADDRESS 0x08220F00u
#else
#define GERMAN_PLAYER_CONTROLLER_TABLE_ADDRESS 0x08207D68u
#endif

#endif
