#ifndef GERMAN_RUBY_POKEMON_DATA_ACCESS_H
#define GERMAN_RUBY_POKEMON_DATA_ACCESS_H

#define GERMAN_POKEMON_STORAGE_BOXES          14u
#define GERMAN_POKEMON_STORAGE_SLOTS_PER_BOX  30u
#define GERMAN_POKEMON_PARTY_SLOTS             6u
#define GERMAN_POKEMON_MOVE_SLOTS              4u
#define GERMAN_POKEMON_PPUP_BITS_PER_MOVE      2u
#define GERMAN_POKEMON_ABILITY_SLOTS           2u

#endif
