#ifndef GERMAN_RUBY_POKEMON_METADATA_H
#define GERMAN_RUBY_POKEMON_METADATA_H

#define GERMAN_NATURE_COUNT                    25u
#define GERMAN_EVOLUTION_ENTRIES_PER_SPECIES    5u
#define GERMAN_FRIENDSHIP_EVOLUTION_THRESHOLD 220u
#define GERMAN_TMHM_LEARNSET_BITS              64u
#define GERMAN_LEVELUP_EXPORT_LIMIT             20u
#define GERMAN_SHINY_XOR_THRESHOLD               8u

#endif
