#ifndef GERMAN_RUBY_TRADE_H
#define GERMAN_RUBY_TRADE_H

#define GERMAN_TRADE_PARTIES                 2u
#define GERMAN_TRADE_PARTY_SLOTS             6u
#define GERMAN_TRADE_SELECTIONS_WITH_CANCEL 13u
#define GERMAN_TRADE_LINK_DATA_U16           20u

#define GERMAN_TRADE_MARKER_ABCD 0xABCDu
#define GERMAN_TRADE_MARKER_DCBA 0xDCBAu

#endif
